# Generated by Django 3.2.25 on 2025-05-04 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ages', '0003_alter_agesverification_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agesverification',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 4, 11, 49, 55, 142479)),
        ),
    ]
